import type { Exercise, ExercisePattern } from './types';

/**
 * Exercise library.
 *
 * `technicalDemand`, `fatigueCost` and `jointStress` are the three fields the
 * generator actually reasons over: technical demand gates beginners, fatigue
 * cost caps total session load for under-slept users, and joint stress is
 * downweighted when injury recovery is a goal.
 */
export const EXERCISES: Exercise[] = [
  // --- Squat pattern ---
  {
    id: 'back-squat',
    name: 'Barbell Back Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'core'],
    equipment: ['barbell'],
    technicalDemand: 3,
    fatigueCost: 3,
    compound: true,
    jointStress: 3,
    cues: ['Brace before you descend, not after', 'Knees track over mid-foot', 'Drive the floor away rather than "standing up"'],
  },
  {
    id: 'front-squat',
    name: 'Front Squat',
    pattern: 'squat',
    primary: ['quads'],
    secondary: ['core', 'glutes'],
    equipment: ['barbell'],
    technicalDemand: 3,
    fatigueCost: 3,
    compound: true,
    jointStress: 2,
    cues: ['Elbows high throughout', 'Stay upright — let the knees travel forward'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['core'],
    equipment: ['dumbbell', 'kettlebell'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Hold the weight tight to your chest', 'Sit between your hips, not back'],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    pattern: 'squat',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    equipment: ['machine'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Do not let your lower back round off the pad at the bottom'],
  },

  // --- Hinge pattern ---
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes', 'back'],
    secondary: ['core'],
    equipment: ['barbell'],
    technicalDemand: 3,
    fatigueCost: 3,
    compound: true,
    jointStress: 3,
    cues: ['Take the slack out of the bar before you pull', 'Push the floor away, do not yank', 'Hips and shoulders rise together'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['back'],
    equipment: ['barbell', 'dumbbell'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: true,
    jointStress: 2,
    cues: ['Push your hips back, do not bend forward', 'Stop when your hamstrings stop, not when the bar hits the floor'],
  },
  {
    id: 'hip-thrust',
    name: 'Barbell Hip Thrust',
    pattern: 'hinge',
    primary: ['glutes'],
    secondary: ['hamstrings'],
    equipment: ['barbell'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Tuck your chin and ribs down', 'Pause and squeeze at the top'],
  },
  {
    id: 'back-extension',
    name: 'Back Extension',
    pattern: 'hinge',
    primary: ['hamstrings', 'glutes'],
    secondary: ['back'],
    equipment: ['machine', 'bodyweight'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Move from the hips, not the lower back'],
  },

  // --- Horizontal push ---
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    pattern: 'horizontal_push',
    primary: ['chest'],
    secondary: ['triceps', 'shoulders'],
    equipment: ['barbell'],
    technicalDemand: 2,
    fatigueCost: 3,
    compound: true,
    jointStress: 2,
    cues: ['Shoulder blades pinned down and back', 'Touch the bar to your lower chest', 'Always use a spotter or safety pins'],
  },
  {
    id: 'db-bench-press',
    name: 'Dumbbell Bench Press',
    pattern: 'horizontal_push',
    primary: ['chest'],
    secondary: ['triceps', 'shoulders'],
    equipment: ['dumbbell'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Let the dumbbells travel slightly wider than a bar path'],
  },
  {
    id: 'incline-db-press',
    name: 'Incline Dumbbell Press',
    pattern: 'horizontal_push',
    primary: ['chest', 'shoulders'],
    secondary: ['triceps'],
    equipment: ['dumbbell'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['30 degrees is enough — steeper turns it into a shoulder press'],
  },
  {
    id: 'push-up',
    name: 'Push-Up',
    pattern: 'horizontal_push',
    primary: ['chest'],
    secondary: ['triceps', 'core'],
    equipment: ['bodyweight'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: true,
    jointStress: 1,
    cues: ['Keep a straight line from head to heels', 'Elbows at roughly 45 degrees, not flared'],
  },
  {
    id: 'machine-chest-press',
    name: 'Machine Chest Press',
    pattern: 'horizontal_push',
    primary: ['chest'],
    secondary: ['triceps'],
    equipment: ['machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: true,
    jointStress: 1,
    cues: ['Set the seat so the handles line up with mid-chest'],
  },

  // --- Vertical push ---
  {
    id: 'overhead-press',
    name: 'Standing Overhead Press',
    pattern: 'vertical_push',
    primary: ['shoulders'],
    secondary: ['triceps', 'core'],
    equipment: ['barbell'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: true,
    jointStress: 2,
    cues: ['Squeeze your glutes to stop the lower back arching', 'Move your head back, then through, as the bar passes'],
  },
  {
    id: 'db-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    pattern: 'vertical_push',
    primary: ['shoulders'],
    secondary: ['triceps'],
    equipment: ['dumbbell'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Stop just short of locking out to keep tension on the delts'],
  },

  // --- Horizontal pull ---
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    pattern: 'horizontal_pull',
    primary: ['back'],
    secondary: ['biceps'],
    equipment: ['barbell'],
    technicalDemand: 3,
    fatigueCost: 3,
    compound: true,
    jointStress: 2,
    cues: ['Hinge to roughly 45 degrees and hold it', 'Pull to your belly button, not your chest'],
  },
  {
    id: 'db-row',
    name: 'Single-Arm Dumbbell Row',
    pattern: 'horizontal_pull',
    primary: ['back'],
    secondary: ['biceps'],
    equipment: ['dumbbell'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Let the shoulder blade travel — do not lock it in place'],
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    pattern: 'horizontal_pull',
    primary: ['back'],
    secondary: ['biceps'],
    equipment: ['cable'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Keep your torso still — no rowing back and forth'],
  },
  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Row',
    pattern: 'horizontal_pull',
    primary: ['back'],
    secondary: ['biceps'],
    equipment: ['machine', 'dumbbell'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: true,
    jointStress: 1,
    cues: ['The pad removes the lower back entirely — useful when you are beaten up'],
  },

  // --- Vertical pull ---
  {
    id: 'pull-up',
    name: 'Pull-Up',
    pattern: 'vertical_pull',
    primary: ['back'],
    secondary: ['biceps', 'core'],
    equipment: ['bodyweight'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: true,
    jointStress: 2,
    cues: ['Start from a dead hang', 'Pull your elbows down to your ribs'],
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    pattern: 'vertical_pull',
    primary: ['back'],
    secondary: ['biceps'],
    equipment: ['cable', 'machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: true,
    jointStress: 1,
    cues: ['Lean back slightly and hold that angle throughout'],
  },

  // --- Lunge / unilateral ---
  {
    id: 'walking-lunge',
    name: 'Walking Lunge',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings', 'core'],
    equipment: ['dumbbell', 'bodyweight'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: true,
    jointStress: 2,
    cues: ['Longer steps bias glutes, shorter steps bias quads'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: ['hamstrings'],
    equipment: ['dumbbell', 'bodyweight'],
    technicalDemand: 2,
    fatigueCost: 3,
    compound: true,
    jointStress: 1,
    cues: ['Brutal but low-load on the spine — good when your back needs a break'],
  },
  {
    id: 'step-up',
    name: 'Step-Up',
    pattern: 'lunge',
    primary: ['quads', 'glutes'],
    secondary: [],
    equipment: ['dumbbell', 'bodyweight'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Push through the top foot — do not bounce off the bottom one'],
  },

  // --- Isolation ---
  {
    id: 'leg-curl',
    name: 'Lying Leg Curl',
    pattern: 'isolation',
    primary: ['hamstrings'],
    secondary: [],
    equipment: ['machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Control the lowering — that is where hamstrings get injured'],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    pattern: 'isolation',
    primary: ['quads'],
    secondary: [],
    equipment: ['machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 2,
    cues: ['Pause briefly at the top'],
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    pattern: 'isolation',
    primary: ['calves'],
    secondary: [],
    equipment: ['machine', 'bodyweight'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Full stretch at the bottom, full contraction at the top'],
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    pattern: 'isolation',
    primary: ['shoulders'],
    secondary: [],
    equipment: ['dumbbell', 'cable'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Lead with your elbows', 'Light weight — momentum defeats the point'],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    pattern: 'isolation',
    primary: ['shoulders', 'back'],
    secondary: [],
    equipment: ['cable'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Pull to your forehead and rotate outward', 'The best single insurance policy for bench-heavy shoulders'],
  },
  {
    id: 'db-curl',
    name: 'Dumbbell Curl',
    pattern: 'isolation',
    primary: ['biceps'],
    secondary: [],
    equipment: ['dumbbell'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Keep your elbows pinned to your sides'],
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    pattern: 'isolation',
    primary: ['biceps'],
    secondary: [],
    equipment: ['cable'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Constant tension through the whole range'],
  },
  {
    id: 'triceps-pushdown',
    name: 'Triceps Pushdown',
    pattern: 'isolation',
    primary: ['triceps'],
    secondary: [],
    equipment: ['cable'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Elbows stay at your sides'],
  },
  {
    id: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    pattern: 'isolation',
    primary: ['triceps'],
    secondary: [],
    equipment: ['dumbbell', 'cable'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['The overhead position trains the long head, which the pushdown misses'],
  },
  {
    id: 'chest-fly',
    name: 'Cable Chest Fly',
    pattern: 'isolation',
    primary: ['chest'],
    secondary: [],
    equipment: ['cable', 'machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Soft elbows, held at a fixed angle throughout'],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    pattern: 'isolation',
    primary: ['shoulders'],
    secondary: ['back'],
    equipment: ['dumbbell', 'machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Think about pulling your elbows apart'],
  },

  // --- Core ---
  {
    id: 'plank',
    name: 'Plank',
    pattern: 'carry',
    primary: ['core'],
    secondary: [],
    equipment: ['bodyweight'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Squeeze glutes and ribs down — a sagging plank trains nothing'],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    pattern: 'isolation',
    primary: ['core'],
    secondary: [],
    equipment: ['bodyweight'],
    technicalDemand: 2,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Curl your pelvis up rather than just lifting your legs'],
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    pattern: 'isolation',
    primary: ['core'],
    secondary: [],
    equipment: ['cable'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['Flex your spine — do not just hinge at the hips'],
  },
  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    pattern: 'carry',
    primary: ['core'],
    secondary: ['back', 'full_body'],
    equipment: ['dumbbell', 'kettlebell'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: true,
    jointStress: 1,
    cues: ['Stand tall, walk normally, do not lean'],
  },

  // --- Conditioning ---
  {
    id: 'incline-walk',
    name: 'Incline Treadmill Walk',
    pattern: 'conditioning',
    primary: ['full_body'],
    secondary: [],
    equipment: ['machine'],
    technicalDemand: 1,
    fatigueCost: 1,
    compound: false,
    jointStress: 1,
    cues: ['The highest-value cardio for anyone lifting — barely interferes with recovery'],
  },
  {
    id: 'bike-intervals',
    name: 'Stationary Bike Intervals',
    pattern: 'conditioning',
    primary: ['full_body'],
    secondary: ['quads'],
    equipment: ['machine'],
    technicalDemand: 1,
    fatigueCost: 2,
    compound: false,
    jointStress: 1,
    cues: ['30 seconds hard, 90 seconds easy'],
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    pattern: 'conditioning',
    primary: ['full_body'],
    secondary: ['back'],
    equipment: ['machine'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: false,
    jointStress: 1,
    cues: ['Legs, then back, then arms — reverse it on the way in'],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    pattern: 'conditioning',
    primary: ['calves', 'full_body'],
    secondary: [],
    equipment: ['none'],
    technicalDemand: 2,
    fatigueCost: 2,
    compound: false,
    jointStress: 3,
    cues: ['Impact loading — genuinely useful for bone density, hard on the knees if you are heavy'],
  },
];

const BY_ID = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return BY_ID.get(id);
}

export function exercisesByPattern(pattern: ExercisePattern): Exercise[] {
  return EXERCISES.filter((e) => e.pattern === pattern);
}
