import type { Peptide } from '../types';

/**
 * Growth-hormone axis compounds: secretagogues, GHRH analogues, and the
 * downstream hormones themselves.
 *
 * Two structural facts shape everything in this file:
 *
 * 1. GHRH analogues and GHRPs act on *different* receptors and are synergistic.
 *    That is why they are almost always stacked — and why stacking them
 *    multiplies the side-effect load rather than adding to it.
 * 2. Everything here raises IGF-1. IGF-1 is mitogenic, drives sebum production,
 *    causes fluid retention, and antagonises insulin. Those four consequences
 *    account for nearly every warning in this category.
 */
export const GROWTH_PEPTIDES: Peptide[] = [
  {
    id: 'ipamorelin',
    name: 'Ipamorelin',
    aliases: ['NNC 26-0161'],
    classes: ['ghrp_secretagogue'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'The most selective of the growth hormone releasing peptides. Raises GH with little effect on cortisol, prolactin or appetite — which is why it is the usual starting point in this class.',
    mechanism:
      'Agonist at the ghrelin receptor (GHS-R1a) in the pituitary, triggering a GH pulse. Unlike GHRP-6 and GHRP-2 it does not meaningfully stimulate appetite or the adrenal axis.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'per_kg',
      low: 1,
      typical: 2,
      high: 3,
      hardMax: 300,
      titrationWeeks: 2,
      note: 'Community protocols scale at roughly 1–3 mcg per kg per injection. The pituitary response saturates around 100–300 mcg — going higher increases side effects, not GH release.',
    },
    frequency: {
      timesPerDay: 2,
      daysPerWeek: 5,
      preferredTimes: ['bedtime', 'post_workout'],
      timingRationale:
        'Injected on an empty stomach — at least 2 hours after eating and 20–30 minutes before food. Carbohydrate and fat blunt the GH pulse. Bedtime dosing rides the natural nocturnal pulse; post-workout is the common second slot.',
    },
    cycle: {
      onWeeks: 12,
      offWeeks: 4,
      maxConsecutiveCycles: 3,
      rationale:
        'Ipamorelin causes less receptor desensitisation than other GHRPs, but breaks are still used to let the axis reset and to reassess whether it is doing anything.',
    },
    goalFit: {
      build_muscle: 3,
      injury_recovery: 3,
      sleep_quality: 4,
      lose_fat: 2,
      bone_density: 2,
      skin_quality: 2,
      gain_weight: 1,
      acne_control: -2,
      metabolic_health: -1,
    },
    sideEffects: [
      { label: 'Head rush or flushing after injection', severity: 'mild', likelihood: 'common', detail: 'Usually passes within a few minutes.' },
      { label: 'Water retention', severity: 'mild', likelihood: 'common' },
      { label: 'Tingling or numbness in the hands', severity: 'moderate', likelihood: 'uncommon', detail: 'Early carpal tunnel from fluid retention. A signal to reduce the dose.' },
      { label: 'Joint aches', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Vivid dreams or lighter sleep', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Reduced insulin sensitivity', severity: 'moderate', likelihood: 'uncommon', detail: 'Less pronounced than with HGH, but present at higher doses.' },
      { label: 'Acne and oily skin', severity: 'mild', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Raising GH and IGF-1 with an active malignancy is contraindicated — IGF-1 promotes cell proliferation and inhibits apoptosis.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Interferes with an actively developing GH axis and open growth plates.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Needs oncology clearance.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'GH opposes insulin; glycaemic control can worsen.' },
      { flag: 'prediabetes', kind: 'relative', reason: 'Can worsen borderline insulin resistance.' },
      { flag: 'carpal_tunnel', kind: 'relative', reason: 'Fluid retention worsens existing nerve compression.' },
      { flag: 'sleep_apnea', kind: 'relative', reason: 'Soft-tissue fluid retention can worsen airway obstruction.' },
    ],
    redFlags: [
      { symptom: 'Persistent hand numbness, weakness, or dropping objects', action: 'Stop and get assessed — prolonged median nerve compression causes permanent damage.' },
      { symptom: 'Rapid unexplained swelling of the face, hands or feet', action: 'Stop and seek medical advice.' },
    ],
    monitoring: ['IGF-1 at baseline and every 8–12 weeks, aiming to stay within the age-appropriate reference range', 'Fasting glucose and HbA1c', 'Blood pressure'],
    bannedInSport: true,
    sources: [
      'Raun et al., Ipamorelin, the first selective growth hormone secretagogue (European Journal of Endocrinology, 1998)',
      'WADA Prohibited List — growth hormone secretagogues, class S2',
    ],
    notes: [
      'Human data are limited to short pharmacology studies. Nobody has run a controlled trial of ipamorelin for muscle gain in healthy trained adults.',
    ],
  },

  {
    id: 'mod-grf-1-29',
    name: 'Mod GRF (1-29)',
    aliases: ['CJC-1295 without DAC', 'Sermorelin analogue', 'Modified GRF 1-29'],
    classes: ['ghrh_analog'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'A short-acting GHRH analogue, almost always paired with a GHRP. It sets up the pulse; the GHRP triggers it.',
    mechanism:
      'Binds the GHRH receptor on pituitary somatotrophs. Four amino acid substitutions protect it from enzymatic breakdown, extending its half-life to about 30 minutes versus a few minutes for native GHRH.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'per_kg',
      low: 1,
      typical: 1.5,
      high: 2,
      hardMax: 150,
      titrationWeeks: 1,
      note: 'Typically dosed around 1–2 mcg per kg, commonly capped near 100 mcg per injection. Doses beyond this do not produce a larger pulse — the pituitary reserve is the limit.',
    },
    frequency: {
      timesPerDay: 2,
      daysPerWeek: 5,
      preferredTimes: ['bedtime', 'post_workout'],
      timingRationale:
        'Injected together with a GHRP in the same syringe, fasted. The 30-minute window before eating matters — carbohydrate blunts the pulse via somatostatin.',
    },
    cycle: {
      onWeeks: 12,
      offWeeks: 4,
      maxConsecutiveCycles: 3,
      rationale: 'Breaks are conventional in this class to limit desensitisation and to reassess IGF-1.',
    },
    goalFit: {
      build_muscle: 3,
      injury_recovery: 3,
      sleep_quality: 3,
      lose_fat: 2,
      bone_density: 2,
      skin_quality: 2,
      acne_control: -2,
      metabolic_health: -1,
    },
    sideEffects: [
      { label: 'Injection-site redness and itching', severity: 'mild', likelihood: 'common' },
      { label: 'Water retention', severity: 'mild', likelihood: 'common' },
      { label: 'Flushing and light-headedness', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Tingling in the hands', severity: 'moderate', likelihood: 'uncommon' },
      { label: 'Reduced insulin sensitivity', severity: 'moderate', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Contraindicated — raises IGF-1, which is mitogenic.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Interferes with normal pubertal GH signalling and growth plates.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Requires oncology clearance.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'Worsens glycaemic control.' },
      { flag: 'prediabetes', kind: 'relative', reason: 'Worsens insulin resistance.' },
      { flag: 'sleep_apnea', kind: 'relative', reason: 'Fluid retention can worsen airway obstruction.' },
    ],
    redFlags: [{ symptom: 'Persistent hand numbness or weakness', action: 'Reduce dose or stop; get assessed if it does not resolve.' }],
    monitoring: ['IGF-1 every 8–12 weeks', 'Fasting glucose and HbA1c'],
    bannedInSport: true,
    sources: [
      'Teichman et al., prolonged GH and IGF-1 increases with CJC-1295 (Journal of Clinical Endocrinology & Metabolism, 2006)',
      'WADA Prohibited List, class S2',
    ],
    notes: [
      'Frequently mislabelled. "CJC-1295" sold without the DAC modification is this compound and lasts about 30 minutes, not 8 days. Check which one you actually have — the dosing schedules are completely different.',
    ],
  },

  {
    id: 'cjc-1295-dac',
    name: 'CJC-1295 with DAC',
    aliases: ['DAC:GRF', 'CJC-1295 DAC'],
    classes: ['ghrh_analog'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'Long-acting GHRH analogue. One injection raises GH and IGF-1 for roughly a week — which also means a mistake stays with you for a week.',
    mechanism:
      'A drug affinity complex (DAC) binds the peptide to circulating albumin, extending its half-life to around 6–8 days. This produces a sustained GH elevation rather than discrete pulses.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'fixed',
      low: 500,
      typical: 1000,
      high: 2000,
      hardMax: 2000,
      titrationWeeks: 2,
      note: 'Commonly 1–2 mg once or twice weekly. Because it accumulates, IGF-1 keeps climbing for 2–3 weeks before it plateaus — judge the dose at week 3, not week 1.',
    },
    frequency: {
      timesPerDay: 1,
      daysPerWeek: 2,
      fixedDays: [0, 3],
      preferredTimes: ['bedtime'],
      timingRationale:
        'The long half-life makes timing largely irrelevant. Twice-weekly dosing keeps blood levels steadier than a single weekly injection.',
    },
    cycle: {
      onWeeks: 12,
      offWeeks: 6,
      maxConsecutiveCycles: 2,
      rationale:
        'The sustained (rather than pulsatile) GH elevation is less physiological than short-acting options, so longer washouts are advised. Allow 2 weeks for levels to clear after the last dose.',
    },
    goalFit: {
      build_muscle: 3,
      injury_recovery: 3,
      sleep_quality: 2,
      bone_density: 2,
      lose_fat: 2,
      skin_quality: 2,
      acne_control: -3,
      metabolic_health: -2,
    },
    sideEffects: [
      { label: 'Water retention and puffiness', severity: 'moderate', likelihood: 'common', detail: 'More pronounced than with short-acting options because GH stays elevated continuously.' },
      { label: 'Joint and muscle aches', severity: 'moderate', likelihood: 'common' },
      { label: 'Carpal tunnel symptoms', severity: 'moderate', likelihood: 'common' },
      { label: 'Reduced insulin sensitivity', severity: 'moderate', likelihood: 'common', detail: 'Continuous GH elevation affects glucose more than pulsatile release does.' },
      { label: 'Acne and oily skin', severity: 'mild', likelihood: 'common' },
      { label: 'Lethargy', severity: 'mild', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Sustained IGF-1 elevation is contraindicated with active malignancy.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Growth plates and developing endocrine axis.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Needs oncology clearance.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'Continuous GH elevation meaningfully worsens glycaemic control.' },
      { flag: 'prediabetes', kind: 'relative', reason: 'Can tip into overt dysglycaemia.' },
      { flag: 'carpal_tunnel', kind: 'relative', reason: 'Reliably worsened.' },
      { flag: 'sleep_apnea', kind: 'relative', reason: 'Fluid retention worsens obstruction.' },
      { flag: 'hypertension', kind: 'relative', reason: 'Fluid retention raises blood pressure.' },
    ],
    redFlags: [
      { symptom: 'Persistent hand numbness or weakness', action: 'Stop — with a week-long half-life you cannot simply skip a dose to fix this quickly.' },
      { symptom: 'Excessive thirst, frequent urination, blurred vision', action: 'Check blood glucose and seek medical advice.' },
    ],
    monitoring: ['IGF-1 at baseline and at week 3, then every 8 weeks', 'Fasting glucose and HbA1c', 'Blood pressure and weight for fluid shifts'],
    bannedInSport: true,
    sources: [
      'Teichman et al., CJC-1295 pharmacokinetics and GH/IGF-1 response (JCEM, 2006)',
      'WADA Prohibited List, class S2',
    ],
    notes: [
      'A clinical development programme for CJC-1295 was halted after a death in a trial of a related long-acting GHRH compound. The causal link was never established, but this compound never completed development — it is not a shelved-for-commercial-reasons drug.',
    ],
  },

  {
    id: 'sermorelin',
    name: 'Sermorelin',
    aliases: ['GHRH (1-29)', 'Geref'],
    classes: ['ghrh_analog'],
    legalStatus: 'prescription',
    evidence: 'B',
    summary:
      'The first 29 amino acids of natural GHRH. Previously an approved medicine for paediatric GH deficiency; now mostly supplied by compounding pharmacies.',
    mechanism:
      'Identical to the active fragment of endogenous GHRH. Stimulates pituitary GH release while preserving normal pulsatility and negative feedback, which makes overdose harder than with exogenous HGH.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'fixed',
      low: 200,
      typical: 300,
      high: 500,
      hardMax: 1000,
      titrationWeeks: 2,
      note: 'Typically 200–500 mcg once nightly. Very short half-life (about 10–20 minutes), so it must be timed to the nocturnal GH pulse to do anything.',
    },
    frequency: {
      timesPerDay: 1,
      daysPerWeek: 7,
      preferredTimes: ['bedtime'],
      timingRationale:
        'Taken at bedtime on an empty stomach so it amplifies the largest natural GH pulse, which occurs in early slow-wave sleep.',
    },
    cycle: {
      onWeeks: 16,
      offWeeks: 4,
      maxConsecutiveCycles: 3,
      rationale: 'Preserved feedback makes it more forgiving than other GH-axis options, but IGF-1 should still be rechecked between cycles.',
    },
    goalFit: {
      build_muscle: 2,
      sleep_quality: 4,
      injury_recovery: 2,
      bone_density: 2,
      lose_fat: 2,
      skin_quality: 2,
      acne_control: -1,
      metabolic_health: -1,
    },
    sideEffects: [
      { label: 'Injection-site pain or redness', severity: 'mild', likelihood: 'common' },
      { label: 'Flushing', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Headache', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Dizziness', severity: 'mild', likelihood: 'rare' },
      { label: 'Water retention', severity: 'mild', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Contraindicated — raises GH and IGF-1.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'Not established as safe.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Paediatric use is a specialist decision — self-directed use with open growth plates is not safe.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Oncology clearance required.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'GH opposes insulin action.' },
    ],
    redFlags: [{ symptom: 'Severe headache with visual changes', action: 'Seek urgent medical assessment.' }],
    monitoring: ['IGF-1 at baseline and every 12 weeks', 'Thyroid function — hypothyroidism blunts the response', 'Fasting glucose'],
    bannedInSport: true,
    sources: [
      'FDA prescribing information — Geref (sermorelin acetate), withdrawn from the US market in 2008 for commercial reasons',
      'Walker, Sermorelin review of clinical use (Clinical Interventions in Aging, 2006)',
    ],
  },

  {
    id: 'ghrp-2',
    name: 'GHRP-2',
    aliases: ['Pralmorelin', 'KP-102'],
    classes: ['ghrp_secretagogue'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'A potent GH releasing peptide. Stronger GH release than ipamorelin, but it also raises prolactin and cortisol and stimulates appetite.',
    mechanism:
      'Ghrelin receptor agonist. Less selective than ipamorelin — it also drives ACTH/cortisol and prolactin release, which is the source of its extra side effects.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'per_kg',
      low: 1,
      typical: 1.5,
      high: 2,
      hardMax: 200,
      titrationWeeks: 2,
      note: 'Roughly 1–2 mcg per kg per injection. GH release saturates near 100–200 mcg; higher doses mostly add cortisol and prolactin.',
    },
    frequency: {
      timesPerDay: 2,
      daysPerWeek: 5,
      preferredTimes: ['bedtime', 'post_workout'],
      timingRationale: 'Fasted dosing, 20–30 minutes before food. Bedtime and post-workout are the standard slots.',
    },
    cycle: {
      onWeeks: 8,
      offWeeks: 4,
      maxConsecutiveCycles: 3,
      rationale: 'Shorter cycles than ipamorelin because desensitisation and cortisol elevation build with continuous use.',
    },
    goalFit: {
      build_muscle: 3,
      gain_weight: 3,
      sleep_quality: 3,
      injury_recovery: 2,
      bone_density: 2,
      acne_control: -2,
      metabolic_health: -2,
      lose_fat: -1,
    },
    sideEffects: [
      { label: 'Increased appetite', severity: 'mild', likelihood: 'common', detail: 'Helpful if you are trying to gain weight, unhelpful if you are cutting.' },
      { label: 'Raised prolactin', severity: 'moderate', likelihood: 'uncommon', detail: 'Can cause breast tenderness or reduced libido at higher doses.' },
      { label: 'Raised cortisol', severity: 'moderate', likelihood: 'uncommon', detail: 'Counterproductive for both muscle gain and sleep quality.' },
      { label: 'Water retention', severity: 'mild', likelihood: 'common' },
      { label: 'Tingling in the hands', severity: 'moderate', likelihood: 'uncommon' },
      { label: 'Reduced insulin sensitivity', severity: 'moderate', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Raises IGF-1.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Developing endocrine axis and open growth plates.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Oncology clearance required.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'GH and cortisol both oppose insulin.' },
      { flag: 'prediabetes', kind: 'relative', reason: 'Compounded glycaemic effect from GH plus cortisol.' },
      { flag: 'eating_disorder_history', kind: 'relative', reason: 'Strong appetite stimulation can be destabilising.' },
      { flag: 'sleep_apnea', kind: 'relative', reason: 'Fluid retention worsens obstruction.' },
    ],
    redFlags: [
      { symptom: 'Breast tenderness or nipple discharge', action: 'Stop and get prolactin measured.' },
      { symptom: 'Persistent hand numbness', action: 'Reduce dose or stop.' },
    ],
    monitoring: ['IGF-1 every 8–12 weeks', 'Prolactin if you notice breast tenderness or libido changes', 'Fasting glucose and HbA1c'],
    bannedInSport: true,
    sources: [
      'Bowers et al., GHRP-2 GH-releasing activity in humans (JCEM, 1990s pharmacology studies)',
      'WADA Prohibited List, class S2',
    ],
  },

  {
    id: 'ghrp-6',
    name: 'GHRP-6',
    aliases: ['Growth Hormone Releasing Hexapeptide'],
    classes: ['ghrp_secretagogue'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'The hunger peptide. Produces intense appetite stimulation alongside GH release — the reason it is used for weight gain rather than for physique work.',
    mechanism:
      'Ghrelin receptor agonist with the strongest orexigenic (appetite-driving) effect of the common GHRPs, since it most closely mimics ghrelin action at the hypothalamus.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'per_kg',
      low: 1,
      typical: 1.5,
      high: 2,
      hardMax: 200,
      titrationWeeks: 2,
      note: 'About 1–2 mcg per kg per injection. Response saturates near 100–200 mcg.',
    },
    frequency: {
      timesPerDay: 2,
      daysPerWeek: 5,
      preferredTimes: ['bedtime', 'morning'],
      timingRationale:
        'Fasted, 20 minutes before a meal — the hunger spike arrives within about 20 minutes and is easiest to use productively right before eating.',
    },
    cycle: {
      onWeeks: 8,
      offWeeks: 4,
      maxConsecutiveCycles: 3,
      rationale: 'Desensitisation develops with continued use, and cortisol/prolactin elevation argues against running it continuously.',
    },
    goalFit: {
      gain_weight: 4,
      build_muscle: 3,
      sleep_quality: 2,
      injury_recovery: 2,
      lose_fat: -3,
      metabolic_health: -2,
      acne_control: -2,
    },
    sideEffects: [
      { label: 'Intense hunger', severity: 'moderate', likelihood: 'common', detail: 'Strong enough that people cutting weight usually cannot tolerate it.' },
      { label: 'Raised cortisol and prolactin', severity: 'moderate', likelihood: 'common', detail: 'More pronounced than with GHRP-2.' },
      { label: 'Water retention', severity: 'mild', likelihood: 'common' },
      { label: 'Head rush and flushing', severity: 'mild', likelihood: 'common' },
      { label: 'Lethargy', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Reduced insulin sensitivity', severity: 'moderate', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Raises IGF-1.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Developing endocrine axis.' },
      { flag: 'eating_disorder_history', kind: 'absolute', reason: 'Overwhelming induced hunger is genuinely dangerous with a binge-eating history.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Oncology clearance required.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'Appetite stimulation plus GH-driven insulin resistance is a poor combination.' },
      { flag: 'prediabetes', kind: 'relative', reason: 'Same concern.' },
    ],
    redFlags: [
      { symptom: 'Breast tenderness or discharge', action: 'Stop and check prolactin.' },
      { symptom: 'Loss of control over eating', action: 'Stop the compound — this is the expected pharmacology, not a personal failing.' },
    ],
    monitoring: ['IGF-1', 'Prolactin if symptomatic', 'Fasting glucose and HbA1c', 'Bodyweight trend — the appetite effect can overshoot the intended surplus'],
    bannedInSport: true,
    sources: [
      'Bowers et al., GHRP-6 structure and GH-releasing activity (Endocrinology, 1984 onward)',
      'WADA Prohibited List, class S2',
    ],
  },

  {
    id: 'hexarelin',
    name: 'Hexarelin',
    aliases: ['Examorelin'],
    classes: ['ghrp_secretagogue'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'The most potent GHRP per microgram — and the fastest to stop working. Desensitisation is significant within weeks.',
    mechanism:
      'Ghrelin receptor agonist with the highest GH-releasing potency of the group. Also binds CD36 receptors, which is behind its studied cardiac effects.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'mcg',
      basis: 'per_kg',
      low: 0.5,
      typical: 1,
      high: 1.5,
      hardMax: 150,
      titrationWeeks: 1,
      note: 'About 1 mcg per kg, typically capped near 100 mcg. Twice daily at most — three times daily accelerates desensitisation sharply.',
    },
    frequency: {
      timesPerDay: 2,
      daysPerWeek: 5,
      preferredTimes: ['bedtime', 'post_workout'],
      timingRationale: 'Fasted dosing. Frequency is kept low specifically to slow receptor downregulation.',
    },
    cycle: {
      onWeeks: 4,
      offWeeks: 4,
      maxConsecutiveCycles: 2,
      rationale:
        'GH response measurably declines after roughly 2–4 weeks of continuous use. Short cycles are not a stylistic preference here — the compound genuinely stops working.',
    },
    goalFit: {
      build_muscle: 3,
      injury_recovery: 2,
      sleep_quality: 2,
      gain_weight: 2,
      acne_control: -2,
      metabolic_health: -2,
    },
    sideEffects: [
      { label: 'Rapid tolerance', severity: 'moderate', likelihood: 'common', detail: 'The defining drawback. GH response falls substantially within weeks.' },
      { label: 'Raised cortisol and prolactin', severity: 'moderate', likelihood: 'common' },
      { label: 'Water retention', severity: 'mild', likelihood: 'common' },
      { label: 'Increased appetite', severity: 'mild', likelihood: 'common' },
      { label: 'Reduced insulin sensitivity', severity: 'moderate', likelihood: 'uncommon' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Raises IGF-1.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Developing endocrine axis.' },
      { flag: 'cardiac_disease', kind: 'relative', reason: 'Has direct cardiac activity via CD36; not appropriate to self-administer with existing heart disease.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Oncology clearance required.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'Worsens glycaemic control.' },
    ],
    redFlags: [{ symptom: 'Palpitations or chest discomfort', action: 'Stop and seek medical assessment.' }],
    monitoring: ['IGF-1', 'Prolactin and cortisol if symptomatic', 'Fasting glucose'],
    bannedInSport: true,
    sources: [
      'Imbimbo et al., hexarelin GH-releasing activity and tolerance in humans (JCEM, 1994)',
      'WADA Prohibited List, class S2',
    ],
  },

  {
    id: 'mk-677',
    name: 'MK-677 (Ibutamoren)',
    aliases: ['Ibutamoren', 'MK-0677'],
    classes: ['ghrp_secretagogue', 'metabolic_oral'],
    legalStatus: 'research_chemical',
    evidence: 'B',
    summary:
      'An orally active, long-acting GH secretagogue. Unusually for this category it has real human trial data — which is also how we know it worsens insulin sensitivity.',
    mechanism:
      'Non-peptide ghrelin receptor agonist with roughly 24-hour activity. Raises GH and IGF-1 continuously rather than in pulses, and drives appetite strongly.',
    routes: ['oral'],
    dosing: {
      unit: 'mg',
      basis: 'fixed',
      low: 10,
      typical: 12.5,
      high: 25,
      hardMax: 25,
      titrationWeeks: 2,
      note: 'Trials used 10–25 mg once daily. Side effects — water retention, appetite, lethargy — scale steeply above about 15 mg, while IGF-1 gains flatten.',
    },
    frequency: {
      timesPerDay: 1,
      daysPerWeek: 7,
      preferredTimes: ['bedtime'],
      timingRationale:
        'Bedtime dosing is standard because the sedating effect is useful then. Some users find it disrupts sleep instead and move it to the morning — either is reasonable.',
    },
    cycle: {
      onWeeks: 12,
      offWeeks: 8,
      maxConsecutiveCycles: 2,
      rationale:
        'Long off periods because the insulin-sensitivity impairment accumulates and needs time to reverse. Fasting glucose should return to baseline before restarting.',
    },
    goalFit: {
      gain_weight: 4,
      build_muscle: 3,
      sleep_quality: 3,
      bone_density: 3,
      injury_recovery: 2,
      skin_quality: 1,
      lose_fat: -2,
      metabolic_health: -3,
      acne_control: -3,
    },
    sideEffects: [
      { label: 'Strong increase in appetite', severity: 'moderate', likelihood: 'common' },
      { label: 'Water retention and puffiness', severity: 'moderate', likelihood: 'common', detail: 'Often several kilograms of scale weight in the first two weeks. This is fluid, not muscle.' },
      { label: 'Raised fasting glucose and reduced insulin sensitivity', severity: 'moderate', likelihood: 'common', detail: 'Documented in controlled trials. The most important downside of this compound.' },
      { label: 'Lethargy and daytime sleepiness', severity: 'mild', likelihood: 'common' },
      { label: 'Numbness or tingling in the hands', severity: 'moderate', likelihood: 'common' },
      { label: 'Muscle and joint aches', severity: 'mild', likelihood: 'uncommon' },
      { label: 'Acne and oily skin', severity: 'mild', likelihood: 'common' },
      { label: 'Increased blood pressure', severity: 'moderate', likelihood: 'uncommon' },
      { label: 'Congestive heart failure signal in frail elderly trial participants', severity: 'severe', likelihood: 'rare', detail: 'One trial in frail elderly adults was stopped early for this. Relevance to healthy young users is unclear but not zero.' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Sustained IGF-1 elevation is contraindicated with active malignancy.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Interferes with a developing GH axis and open growth plates.' },
      { flag: 'diabetes_t1', kind: 'absolute', reason: 'Directly opposes insulin action with continuous, not pulsatile, GH elevation.' },
      { flag: 'diabetes_t2', kind: 'absolute', reason: 'The insulin-sensitivity impairment is documented and dose-dependent — this is not a manageable trade-off with existing diabetes.' },
      { flag: 'cardiac_disease', kind: 'absolute', reason: 'Fluid retention plus the heart failure signal in trials makes this unsafe with existing cardiac disease.' },
      { flag: 'prediabetes', kind: 'relative', reason: 'Likely to push you into the diabetic range. Needs close glucose monitoring.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Oncology clearance required.' },
      { flag: 'hypertension', kind: 'relative', reason: 'Fluid retention raises blood pressure further.' },
      { flag: 'sleep_apnea', kind: 'relative', reason: 'Fluid retention worsens airway obstruction.' },
      { flag: 'carpal_tunnel', kind: 'relative', reason: 'Reliably worsened by fluid retention.' },
    ],
    redFlags: [
      { symptom: 'Shortness of breath when lying flat, or swelling in both ankles', action: 'Stop and seek medical care — these are heart failure symptoms.' },
      { symptom: 'Excessive thirst, frequent urination, blurred vision', action: 'Check blood glucose; stop if elevated.' },
      { symptom: 'Persistent hand numbness or weakness', action: 'Reduce dose or stop.' },
    ],
    monitoring: [
      'Fasting glucose and HbA1c at baseline, week 4, and every 8 weeks — this is the non-negotiable one',
      'IGF-1 every 8–12 weeks',
      'Blood pressure',
      'Bodyweight, understanding that early gains are water',
    ],
    bannedInSport: true,
    sources: [
      'Nass et al., MK-677 in healthy older adults, 2-year RCT (Annals of Internal Medicine, 2008)',
      'Murphy et al., MK-677 effects on GH, IGF-1 and glucose metabolism (JCEM, 1998)',
      'WADA Prohibited List, class S2',
    ],
    notes: [
      'Not a peptide — it is an orally active small molecule. Included because it is used interchangeably with peptides in this space.',
      'The 2-year RCT found increased lean mass but no improvement in strength or function, alongside raised fasting glucose. That is the fairest one-line summary of what it does.',
    ],
  },

  {
    id: 'igf-1-lr3',
    name: 'IGF-1 LR3',
    aliases: ['Long R3 IGF-1'],
    classes: ['igf'],
    legalStatus: 'research_chemical',
    evidence: 'C',
    summary:
      'A modified, long-acting form of IGF-1 that bypasses the body\'s binding proteins. Among the highest-risk compounds commonly sold, with acute hypoglycaemia as the immediate danger.',
    mechanism:
      'An IGF-1 analogue with an arginine substitution and a 13-amino-acid extension that prevents binding to IGF binding proteins. This leaves it free and active far longer than natural IGF-1, and it also cross-reacts with the insulin receptor.',
    routes: ['subcutaneous', 'intramuscular'],
    dosing: {
      unit: 'mcg',
      basis: 'fixed',
      low: 0,
      typical: 0,
      high: 0,
      hardMax: 0,
      titrationWeeks: 0,
      note: 'No dose is shown for this compound.',
    },
    doseGuidanceWithheld: {
      reason:
        'IGF-1 LR3 causes dose-dependent hypoglycaemia that can progress to seizure or loss of consciousness, has no human dose-finding data, and is frequently sold underdosed or mislabelled — meaning a "known" dose is not actually known. Publishing a number here would imply a margin of safety that does not exist. The information below is provided so that anyone already using it can recognise danger signs.',
    },
    frequency: {
      timesPerDay: 1,
      daysPerWeek: 5,
      preferredTimes: ['post_workout'],
      timingRationale: 'Not a recommendation. Users typically dose post-workout; the relevant point is that any dose must be taken with carbohydrate available.',
    },
    cycle: {
      onWeeks: 4,
      offWeeks: 6,
      maxConsecutiveCycles: 1,
      rationale: 'Short exposure limits the accumulated risk from sustained supraphysiological IGF-1 signalling.',
    },
    goalFit: {
      build_muscle: 3,
      gain_weight: 2,
      injury_recovery: 1,
      metabolic_health: -3,
      acne_control: -3,
    },
    sideEffects: [
      { label: 'Hypoglycaemia', severity: 'severe', likelihood: 'common', detail: 'Shakiness, sweating, confusion, and at worst seizure or unconsciousness. The dominant acute risk.' },
      { label: 'Sustained supraphysiological IGF-1 signalling', severity: 'severe', likelihood: 'common', detail: 'Epidemiological work links elevated IGF-1 to increased risk of several cancers. The lifetime implications of deliberately elevating it are unquantified.' },
      { label: 'Organ growth', severity: 'severe', likelihood: 'rare', detail: 'IGF-1 acts on all tissues, not just muscle.' },
      { label: 'Severe acne', severity: 'moderate', likelihood: 'common' },
      { label: 'Joint pain', severity: 'moderate', likelihood: 'common' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'IGF-1 directly promotes proliferation and inhibits apoptosis. This is the clearest contraindication in the entire app.' },
      { flag: 'cancer_history', kind: 'absolute', reason: 'Deliberately raising IGF-1 with any cancer history is not defensible.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No safety data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'No safety data; interferes with development.' },
      { flag: 'diabetes_t1', kind: 'absolute', reason: 'Cross-reactivity with the insulin receptor makes glucose control unpredictable and dangerous.' },
      { flag: 'diabetes_t2', kind: 'absolute', reason: 'Same hypoglycaemia risk.' },
      { flag: 'seizure_disorder', kind: 'absolute', reason: 'Hypoglycaemia lowers the seizure threshold.' },
    ],
    redFlags: [
      { symptom: 'Shakiness, sweating, confusion, blurred vision or intense hunger', action: 'Take fast-acting carbohydrate immediately (glucose tablets, juice, sugar). If confusion worsens or consciousness is lost, this is a medical emergency — call emergency services.' },
      { symptom: 'Any seizure', action: 'Emergency services immediately.' },
    ],
    monitoring: [
      'Never use without fast-acting carbohydrate within arm\'s reach',
      'Never use alone or before sleep',
      'Someone nearby should know what you are taking and what hypoglycaemia looks like',
    ],
    bannedInSport: true,
    sources: [
      'Tomas et al., Long R3 IGF-1 potency and IGFBP resistance (Journal of Endocrinology, 1993)',
      'WADA Prohibited List, class S2',
      'Epidemiological reviews linking circulating IGF-1 to cancer incidence (Lancet Oncology and related meta-analyses)',
    ],
    notes: [
      'The app deliberately shows no dose for this compound. That is a design decision, not a data gap.',
    ],
  },

  {
    id: 'somatropin',
    name: 'Somatropin (HGH)',
    aliases: ['Human Growth Hormone', 'Genotropin', 'Norditropin', 'Omnitrope'],
    classes: ['growth_hormone'],
    legalStatus: 'prescription',
    evidence: 'A',
    summary:
      'Recombinant human growth hormone. A genuine medicine with strong evidence in deficiency states, and a controlled substance for non-medical use in many countries.',
    mechanism:
      'Replaces or supplements endogenous GH, acting directly on tissues and via hepatic IGF-1 production. Unlike secretagogues it bypasses pituitary feedback entirely, so there is no natural ceiling on the level achieved.',
    routes: ['subcutaneous'],
    dosing: {
      unit: 'iu',
      basis: 'fixed',
      low: 0,
      typical: 0,
      high: 0,
      hardMax: 0,
      titrationWeeks: 0,
      note: 'Dose is set by a prescriber against measured IGF-1 and clinical response.',
    },
    doseGuidanceWithheld: {
      reason:
        'Somatropin dosing is individualised by a clinician against measured IGF-1 levels and the specific indication. It is also a controlled substance for non-medical use in several jurisdictions, including under the US Anabolic Steroid Control Act. This app will not suggest a number — if it is appropriate for you, it comes with a prescription and blood work.',
    },
    frequency: {
      timesPerDay: 1,
      daysPerWeek: 7,
      preferredTimes: ['bedtime'],
      timingRationale: 'Evening dosing mimics the natural nocturnal GH peak. Your prescriber sets the actual schedule.',
    },
    cycle: {
      onWeeks: 52,
      offWeeks: 0,
      maxConsecutiveCycles: null,
      rationale: 'In its approved indications this is continuous replacement therapy, managed clinically.',
    },
    goalFit: {
      build_muscle: 3,
      injury_recovery: 3,
      lose_fat: 3,
      bone_density: 4,
      skin_quality: 2,
      sleep_quality: 1,
      metabolic_health: -3,
      acne_control: -2,
    },
    sideEffects: [
      { label: 'Fluid retention and swelling', severity: 'moderate', likelihood: 'common' },
      { label: 'Joint and muscle pain', severity: 'moderate', likelihood: 'common' },
      { label: 'Carpal tunnel syndrome', severity: 'moderate', likelihood: 'common' },
      { label: 'Insulin resistance and raised blood glucose', severity: 'severe', likelihood: 'common', detail: 'Can precipitate type 2 diabetes at supraphysiological doses.' },
      { label: 'Acromegalic changes with long-term high-dose use', severity: 'severe', likelihood: 'uncommon', detail: 'Enlargement of hands, feet, jaw and internal organs including the heart. Largely irreversible.' },
      { label: 'Cardiomyopathy', severity: 'severe', likelihood: 'rare' },
      { label: 'Increased intracranial pressure', severity: 'severe', likelihood: 'rare' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Labelled contraindication — GH is mitogenic.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'Not established as safe.' },
      { flag: 'under_18', kind: 'absolute', reason: 'Paediatric GH therapy is a specialist endocrinology decision. Self-directed use with open growth plates can cause irreversible skeletal changes.' },
      { flag: 'diabetes_t1', kind: 'absolute', reason: 'Requires specialist management of the insulin interaction.' },
      { flag: 'diabetes_t2', kind: 'relative', reason: 'Will worsen control; needs medication adjustment.' },
      { flag: 'cancer_history', kind: 'relative', reason: 'Oncology clearance required.' },
      { flag: 'retinopathy', kind: 'relative', reason: 'Proliferative retinopathy is a labelled contraindication.' },
      { flag: 'sleep_apnea', kind: 'relative', reason: 'Soft-tissue growth and fluid retention worsen obstruction.' },
      { flag: 'carpal_tunnel', kind: 'relative', reason: 'Commonly and significantly worsened.' },
      { flag: 'cardiac_disease', kind: 'relative', reason: 'Fluid retention and cardiac remodelling risk.' },
    ],
    redFlags: [
      { symptom: 'Severe headache with vomiting or visual changes', action: 'Emergency care — possible raised intracranial pressure.' },
      { symptom: 'Persistent hand numbness or weakness', action: 'Contact your prescriber for a dose reduction.' },
      { symptom: 'Excessive thirst, frequent urination, blurred vision', action: 'Check blood glucose and contact your prescriber.' },
    ],
    monitoring: ['IGF-1 kept within the age-appropriate reference range', 'Fasting glucose and HbA1c', 'Thyroid function — GH can unmask hypothyroidism', 'Blood pressure'],
    bannedInSport: true,
    sources: [
      'FDA prescribing information — Genotropin, Norditropin, Omnitrope (somatropin)',
      'US Anabolic Steroid Control Act 1990, 21 USC 333(e) — distribution of hGH for non-medical use',
      'WADA Prohibited List, class S2',
    ],
  },

  {
    id: 'follistatin-344',
    name: 'Follistatin-344',
    aliases: ['FST-344'],
    classes: ['igf'],
    legalStatus: 'research_chemical',
    evidence: 'D',
    summary:
      'A myostatin-inhibiting protein sold on the promise of unrestricted muscle growth. There is no human safety or efficacy data at all.',
    mechanism:
      'Binds and neutralises myostatin, the principal brake on skeletal muscle growth. In genetically modified animals, removing that brake produces dramatic hypertrophy.',
    routes: ['subcutaneous', 'intramuscular'],
    dosing: {
      unit: 'mcg',
      basis: 'fixed',
      low: 0,
      typical: 0,
      high: 0,
      hardMax: 0,
      titrationWeeks: 0,
      note: 'No dose is shown for this compound.',
    },
    doseGuidanceWithheld: {
      reason:
        'There is no human dosing data of any kind. Myostatin inhibition is not muscle-specific — the pathway is active in cardiac tissue, tendon and vasculature. A related myostatin inhibitor (ACE-031) had its clinical trials halted after participants developed nosebleeds and dilated skin blood vessels. Suggesting a number would be inventing one.',
    },
    frequency: {
      timesPerDay: 1,
      daysPerWeek: 7,
      preferredTimes: ['morning'],
      timingRationale: 'Not applicable — no established protocol exists.',
    },
    cycle: {
      onWeeks: 0,
      offWeeks: 0,
      maxConsecutiveCycles: null,
      rationale: 'No established cycle.',
    },
    goalFit: {
      build_muscle: 1,
      gain_weight: 1,
    },
    sideEffects: [
      { label: 'Unknown — no human data', severity: 'severe', likelihood: 'common', detail: 'This is the honest entry. Nobody knows the human side-effect profile.' },
      { label: 'Effects on non-muscle tissue', severity: 'severe', likelihood: 'uncommon', detail: 'Myostatin signalling is present in heart, tendon and blood vessels. Inhibiting it systemically does not stop at skeletal muscle.' },
      { label: 'Tendon-to-muscle strength mismatch', severity: 'moderate', likelihood: 'uncommon', detail: 'Muscle that outgrows its tendon capacity raises rupture risk.' },
      { label: 'Bleeding and vascular changes', severity: 'severe', likelihood: 'rare', detail: 'Observed with the related agent ACE-031, which led to trial termination.' },
    ],
    contraindications: [
      { flag: 'active_cancer', kind: 'absolute', reason: 'Myostatin/activin signalling is involved in tumour suppression in some tissues.' },
      { flag: 'cancer_history', kind: 'absolute', reason: 'Unquantified risk with no offsetting evidence of benefit.' },
      { flag: 'pregnant_or_breastfeeding', kind: 'absolute', reason: 'No data.' },
      { flag: 'under_18', kind: 'absolute', reason: 'No data.' },
      { flag: 'cardiac_disease', kind: 'absolute', reason: 'Myostatin signalling is active in cardiac muscle; inhibition with existing heart disease is unstudied and unsafe.' },
    ],
    redFlags: [
      { symptom: 'Nosebleeds, unusual bruising, or spidery dilated vessels on the skin', action: 'Stop immediately and seek medical care — this pattern ended the ACE-031 trials.' },
      { symptom: 'Sudden severe pain in a tendon during exertion', action: 'Seek urgent assessment for tendon rupture.' },
    ],
    monitoring: ['There is no established monitoring protocol, which is itself the reason to avoid it.'],
    bannedInSport: true,
    sources: [
      'Lee & McPherron, myostatin regulation of muscle mass (PNAS, 2001)',
      'Attie et al., ACE-031 phase 1 trial and the vascular adverse events that halted development (Muscle & Nerve, 2013)',
      'WADA Prohibited List, class S4.4 — myostatin inhibitors',
    ],
    notes: [
      'Most product sold under this name is unlikely to contain biologically active follistatin at all — it is a large, fragile protein that does not survive typical handling.',
    ],
  },
];
